# Use a Node.js base image
FROM node:14-alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if present) to the working directory
COPY package*.json ./

# Copy the entire project directory into the Docker image
COPY . .

# Expose the port your React app runs on
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]
