version: '3'
services:
  client:
    build:
      context: ./client
    command: npm start
    depends_on:
      - server
      - nats

  server:
    build:
      context: ./server
    command: npm run dev
    depends_on:
      - nats

  nats:
    # Include your existing NATS configuration from nats/docker-compose.yml here
    image: nats:2.10.9-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
      - "5050:5050"
    volumes:
      - ./nats.conf:/usr/src/app/nats.conf
    command: ["nats-server","-c","/usr/src/app/nats.conf"]
